### ISSUE TITLE
Ruby 2.2 - default environment "production" not working

### ISSUE THREAD

**Issue by mikelitton** [phusion/passenger-docker#106]
Hi.

The application tries to find games that are only available for the development environment. It should not try to find "awesome_print" in this stage. Any idea how to fix this problem?

```
[ 2015-09-08 20:17:27.5812 41/7f5d575207c0 age/Ust/Main.cpp:311 ]: Passenger UstRouter online, PID 41
App 55 stdout:
App 55 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 55 stderr:
App 55 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 55 stderr:
App 55 stderr:      Compilation succesful. The logs are here:
App 55 stderr:      /tmp/passenger_native_support-joekcc.log
App 55 stderr:  --> passenger_native_support.so successfully loaded.
App 55 stdout:
[ 2015-09-08 20:18:06.3715 34/7fc73229f700 App/Implementation.cpp:303 ]: Could not spawn process for application /home/app/webapp/back-end: An error occured while starting up the preloader.
  Error ID: 0a0b5b0c
  Error details saved to: /tmp/passenger-error-IDX1Ec.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>app</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
</ol>

<p>-------- The exception is as follows: -------</p>
Could not find awesome_print-1.6.1 in any of the sources (Bundler::GemNotFound)
<pre>  /var/lib/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize&#39;
  /var/lib/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!&#39;
  /var/lib/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize&#39;
  /var/lib/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs&#39;
...
```

Any help or pointers are much appreciated.

**Comment by mikelitton** [comment]
The problem was fixed by adding a configuration file to nginx that passes in variables to passenger such as rails_env
