### ISSUE TITLE
Passenger not starting in staging mode

### ISSUE THREAD

**Issue by joostliketoast** [phusion/passenger-docker#135]
Passenger won't run if i tell it to run in staging mode it will run in other environment names or when i go into the container and run `passenger start`

tested with the following images

```
FROM phusion/passenger-ruby21:0.9.18
FROM phusion/passenger-ruby22:0.9.18
```

error generated by passenger

```
3/23/2016 11:51:56 AM[ 2016-03-23 10:51:47.3455 46/7f459cc407c0 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
3/23/2016 11:51:56 AM[ 2016-03-23 10:51:47.3608 49/7f5651cac7c0 age/Cor/CoreMain.cpp:957 ]: Starting Passenger core...
3/23/2016 11:51:56 AM[ 2016-03-23 10:51:47.3610 49/7f5651cac7c0 age/Cor/CoreMain.cpp:234 ]: Passenger core running in multi-application mode.
3/23/2016 11:51:56 AM[ 2016-03-23 10:51:47.3677 49/7f5651cac7c0 age/Cor/CoreMain.cpp:707 ]: Passenger core online, PID 49
3/23/2016 11:51:56 AM[ 2016-03-23 10:51:47.3757 55/7feb910527c0 age/Ust/UstRouterMain.cpp:504 ]: Starting Passenger UstRouter...
3/23/2016 11:51:56 AM[ 2016-03-23 10:51:47.3793 55/7feb910527c0 age/Ust/UstRouterMain.cpp:317 ]: Passenger UstRouter online, PID 55
3/23/2016 11:52:00 AMApp 78 stdout:
3/23/2016 11:52:01 AMApp 78 stdout:
3/23/2016 11:52:02 AM[ 2016-03-23 10:52:01.0192 49/7f5648b53700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/app/webapp: An error occurred while starting up the preloader.
3/23/2016 11:52:02 AM  Error ID: eh3e4-fw2ALhvhTwl
3/23/2016 11:52:02 AM  Error details saved to: /tmp/passenger-error-1cJAVV.html
3/23/2016 11:52:02 AM  Message from application: cannot load such file -- /home/app/webapp/config/environment (LoadError)
3/23/2016 11:52:02 AM  config.ru:3:in `require'
3/23/2016 11:52:02 AM  config.ru:3:in `block in <main>'
3/23/2016 11:52:02 AM  /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
3/23/2016 11:52:02 AM  /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
3/23/2016 11:52:02 AM  config.ru:1:in `new'
3/23/2016 11:52:02 AM  config.ru:1:in `<main>'
3/23/2016 11:52:02 AM  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
3/23/2016 11:52:02 AM  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
3/23/2016 11:52:02 AM  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
3/23/2016 11:52:02 AM  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
3/23/2016 11:52:02 AM  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

config.ru

```
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment', __FILE__)
run Rails.application
```

environment.rb

```
# Load the Rails application.
require File.expand_path('../application', __FILE__)

# Initialize the Rails application.
Rails.application.initialize!
```

dockerfile

```
FROM phusion/passenger-ruby21:0.9.18

# Set correct environment variables.
ENV HOME /root
ENV RAILS_ENV production

# Use baseimage-docker's init process.
CMD ["/sbin/my_init"]

RUN rm -f /etc/service/nginx/down

RUN rm /etc/nginx/sites-enabled/default
ADD webapp.conf.erb /site_config/conf/webapp.conf.erb
ADD .htpasswd /etc/nginx/.htpasswd
ADD docker/parse_erb.rb /site_config/commands/parse_erb.rb
ADD app-env.conf /etc/nginx/main.d/app-env.conf

RUN mkdir -p /home/app/webapp/tmp/cache/assets
RUN mkdir -p /home/app/webapp/log
COPY . /home/app/webapp
RUN chown -R app:app /home/app/webapp

WORKDIR /home/app/webapp

RUN bundle install --jobs 20

RUN mkdir -p /etc/my_init.d
ADD docker/setup.sh /etc/my_init.d/setup.sh
ADD docker/start.sh /etc/my_init.d/start.sh
RUN chmod +x /etc/my_init.d/setup.sh
RUN chmod +x /etc/my_init.d/start.sh

# run the delayedjob deamon
RUN mkdir /etc/service/delayedjob
ADD delayedjob.sh /etc/service/delayedjob/run
RUN chmod a+x /etc/service/delayedjob/run

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by OnixGH** [comment]
Passenger only [relays the environment value](https://www.phusionpassenger.com/library/config/standalone/reference/#--environment-environment) to rails so it looks like a problem in the app config. The [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) can be used for configuration questions.
