### ISSUE TITLE
Need set ubuntu locale correctly for python

### ISSUE THREAD

**Issue by johnson** [phusion/passenger-docker#157]
http://stackoverflow.com/questions/27931668/encoding-problems-when-running-an-app-in-docker-python-java-ruby-with-u

```
docker run -it --rm phusion/passenger-full:0.9.19 /sbin/my_init -- ls                                                                                                   
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 353, in <module>
    main(args)
  File "/sbin/my_init", line 272, in main
    export_envvars()
  File "/sbin/my_init", line 88, in export_envvars
    f.write(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-9: ordinal not in range(128)
```

This is the minimal correct Dockerfile:

```
FROM ubuntu:lastest

RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8
```

**Comment by OnixGH** [comment]
This issue most likely belongs to the [baseimage](https://github.com/phusion/baseimage-docker). In 0.9.21 we updated to the a baseimage that had some fixes, including [this one](https://github.com/phusion/baseimage-docker/pull/336), and to me it looks like the issue is fixed :
```
docker run -it --rm phusion/passenger-full:0.9.21 /sbin/my_init -- locale
...
*** Running locale...
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
*** locale exited with status 0.
```
