### ISSUE TITLE
RAILS_ENV not present for boot script (even with nginx config)

### ISSUE THREAD

**Issue by binarymason** [phusion/passenger-docker#198]
My setup script is blowing up because `RAILS_ENV` is not in my environment, despite adding whitelist to `/etc/nginx/main.d/*`.

```
bin/setup:16:in `fetch': key not found: "RAILS_ENV" (KeyError)
        from bin/setup:16:in `block in <main>'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
        from bin/setup:13:in `<main>'

```

Interestingly enough, once I `docker run -it example/api:dev /sbin/my_init -- bash -l
`  my setup will fail, but afterwards my environment variables are set correctly and can be observed via `env`.

Am I missing something silly here or is there a bug?

<details>
<summary><b>log from </b><code>docker build</code></summary>

```
Sending build context to Docker daemon   12.8kB
Step 1/15 : FROM phusion/passenger-ruby24
---> c3f873600e95
Step 2/15 : ENV APP_NAME example
---> Running in 86731603a35a
---> 42d51ea8e352
Removing intermediate container 86731603a35a
Step 3/15 : CMD [“/sbin/my_init”]
---> Running in 7249d3fbd573
---> 07fe1b7a4e68
Removing intermediate container 7249d3fbd573
Step 4/15 : ADD boot.sh /etc/my_init.d/boot.sh
---> 9be77d51876d
Step 5/15 : ADD nginx.conf /etc/nginx/sites-enabled/${APP_NAME}.conf
---> f1d599dede80
Step 6/15 : ADD nginx_env.conf /etc/nginx/main.d/env.conf
---> e8b45b543348
Step 7/15 : RUN rm -f /etc/service/nginx/down &&      rm /etc/nginx/sites-enabled/default
---> Running in 3991e1302ce6
---> fbc80a8a45b8
Removing intermediate container 3991e1302ce6
Step 8/15 : EXPOSE 80
---> Running in c5f8995587ee
---> 20fb083c740d
Removing intermediate container c5f8995587ee
Step 9/15 : ADD .ssh/config /home/app/.ssh/config
---> c740c974629e
Step 10/15 : RUN touch /home/app/.ssh/known_hosts &&      ssh-keyscan -H github.com >> /home/app/.ssh/known_hosts &&      chmod 600 /home/app/.ssh/config
---> Running in dd08b4f73ca1
# github.com:22 SSH-2.0-libssh_0.7.0
# github.com:22 SSH-2.0-libssh_0.7.0
# github.com:22 SSH-2.0-libssh_0.7.0
---> e18a804446d0
Removing intermediate container dd08b4f73ca1
Step 11/15 : ADD .ssh/id_rsa /home/app/.ssh/id_rsa
---> 07a762507e01
Step 12/15 : ADD .ssh/id_rsa.pub /home/app/.ssh/id_rsa.pub
---> 6deaf5e6d6e4
Step 13/15 : RUN chmod 600 /home/app/.ssh/id_rsa &&      chmod 644 /home/app/.ssh/id_rsa.pub &&      chown -R app:app /home/app/.ssh
---> Running in 724d500543f3
---> 5bbb10878217
Removing intermediate container 724d500543f3
Step 14/15 : RUN /etc/my_init.d/boot.sh
---> Running in af3e62ffc895
Cloning into '/home/app/api'...
Warning: Permanently added the RSA host key for IP address '<redacted>' to the list of known hosts.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
bin/setup:16:in `fetch': key not found: "RAILS_ENV" (KeyError)
from bin/setup:16:in `block in <main>'
from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
from bin/setup:13:in `<main>'
---> 826345e5654a
Removing intermediate container af3e62ffc895
Step 15/15 : RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*/var/tmp/*
---> Running in 33f5954a9bdc
---> 8b571aeca721
Removing intermediate container 33f5954a9bdc
Successfully built 8b571aeca721
Successfully tagged example/api:dev

```
</details>

<hr/>

<details>
<summary><b>nginx.conf</b></summary>

```
server {
  listen 80 default_server;
  server_name example.com;
  root /home/app/api/public;
  passenger_enabled on;
  passenger_user app;
  passenger_ruby /usr/bin/ruby2.4;
  passenger_app_env production;
}
```
</details>

<details>
<summary><b>nginx_env.conf</b></summary>

```
# set by Passenger Docker
env RAILS_ENV;
env RACK_ENV;
env PASSENGER_APP_ENV;

# set manually
env SECRET_KEY_BASE;
env RDS_USERNAME;
env RDS_DB_NAME;
env RDS_PASSWORD;
env RDS_HOSTNAME;
env RDS_PORT;
```
</details>

<details>
<summary><b>Dockerfile</b></summary>

```
FROM phusion/passenger-ruby24

# set environment variables
ENV APP_NAME=example

# use baseimage-docker’s init process
CMD [“/sbin/my_init”]

# add boot script
ADD boot.sh /etc/my_init.d/boot.sh


# setup nginx
ADD nginx.conf /etc/nginx/sites-enabled/${APP_NAME}.conf
ADD nginx_env.conf /etc/nginx/main.d/env.conf
RUN rm -f /etc/service/nginx/down &&\
      rm /etc/nginx/sites-enabled/default

EXPOSE 80

# allow github as a known host
ADD .ssh/config /home/app/.ssh/config
RUN touch /home/app/.ssh/known_hosts &&\
      ssh-keyscan -H github.com >> /home/app/.ssh/known_hosts &&\
      chmod 600 /home/app/.ssh/config

# add deploy keys
ADD .ssh/id_rsa /home/app/.ssh/id_rsa
ADD .ssh/id_rsa.pub /home/app/.ssh/id_rsa.pub
RUN chmod 600 /home/app/.ssh/id_rsa &&\
      chmod 644 /home/app/.ssh/id_rsa.pub &&\
      chown -R app:app /home/app/.ssh

# boot
RUN /etc/my_init.d/boot.sh

# clean up when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

```
</details>

<details>
<summary><b>boot.sh</b></summary>

```sh
#!/bin/sh

repo="git@github.com:example/api.git"
dir="/home/app/api"
logfile="/var/log/api.log"

mkdir -p /var/log/nginx/

touch "$logfile"
chown -R app:app "$logfile"

chown -R www-data:adm /var/log/nginx/

su - app <<EOF
if [ -d "$dir" ]; then
  cd "$dir"
  git reset --hard
  git clean -fd .
  git checkout master
  git pull
  git reset --hard "origin/master"
else
  git clone "$repo" "$dir" || exit 1
  cd "$dir"
  git checkout master
fi
bin/setup
EOF

chown -R app:app "$dir"

```
</details>

<details>
<summary><b>bin/setup</b></summary>

```rb
#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  # This script is a starting point to setup your application.
  # Add necessary setup steps to this file.
  puts "== Setting up environment:  #{ENV.fetch('RAILS_ENV')} =="

  puts '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system('bundle check') || system!('bundle install')


  # puts "\n== Copying sample files =="
  # unless File.exist?('config/database.yml')
  #   cp 'config/database.yml.sample', 'config/database.yml'
  # end

  puts "\n== Preparing database =="
  system! 'bin/rails db:migrate 2>/dev/null || bin/rails db:setup'


  puts "\n== Removing old logs and tempfiles =="
  system! 'bin/rails log:clear tmp:clear'

  puts "\n== Done. =="

  # puts "\n== Restarting application server =="
  # system! 'bin/rails restart'
end

```
</details>

**Comment by dmitry** [comment]
What about setting up `PASSENGER_APP_ENV` ?

**Comment by CamJN** [comment]
Yes the `passenger_app_env` nginx config options is more reliable.
