### ISSUE TITLE
magic-file.rb:8:in `initialize': No such file or directory @ rb_sysopen - c (Errno::ENOENT)

### ISSUE THREAD

**Issue by nithin-kumar** [phusion/passenger-docker#292]
When we use **phusion/passenger-full:1.0.0** , we are getting following exception

`I, [2020-05-15T11:53:32.959007 #420]  INFO -- sentry: ** [Raven] Raven 2.13.0 ready to catch errors
Loading production environment (Rails 4.2.0)
/usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/magic-file.rb:8:in `initialize': No such file or directory @ rb_sysopen - c (Errno::ENOENT)
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/magic-file.rb:8:in `open'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/magic-file.rb:8:in `open'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/input-method.rb:101:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/context.rb:85:in `new'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/context.rb:85:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:426:in `new'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:426:in `initialize'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:381:in `new'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:381:in `start'
	from /usr/local/rvm/gems/ruby-2.3.8/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.3.8/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.3.8/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.3.8/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.3.8/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'`

**Comment by CamJN** [comment]
Does this still happen with `phusion/passenger-full:latest`?

**Comment by ajhodgson** [comment]
Closing as stale. Please open a new issue if required.
