### ISSUE TITLE
Get a circular dependency warning when using version phusion/passenger-nodejs:1.0.12

### ISSUE THREAD

**Issue by davisarchibald** [phusion/passenger-docker#307]
Coming across some unnecessary noise on `passenger start` after we upgraded our phusion docker instance so that we could run our Node application on the LTS version (14).  From the logs when running it with the `--trace-warnings` argument, it looks to be an issue within passenger and its use of the winston logging lib (might be directly, might not be). (See below for an example stack trace)  As a point of thoroughness, and clarity, I should point out that our application does not get this error if you just run `node server.js` (running this command with version `14.15.1` locally) for example. We only come across this error when using passenger to run our application. Not a vital bug, as the application runs just fine despite the warnings, but it does unnecessarily clog our logs with information and we just end up ignoring as we can't fix it.

1 -What does your software stack look like?
* Node application
* Running passenger in a docker container
* Inside of Kubernetes

2- What operating system and processor architecture are you using?
* See the issue on my local Mac machine when running `passenger start`, seeing it in the docker instance locally as well as in the cloud

3- What did you do? 😱
* Upgraded to the latest version of phusion/passenger to run the application on version 14

4- What did you expect to see?
* No warnings on startup

5- What did you see instead?
* Warnings on startup:
```sh
(node:44707) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object.exports.setLevels (/usr/local/Cellar/passenger/6.0.7_2/libexec/src/nodejs_supportlib/vendor-copy/winston/lib/winston/common.js:35:14)
    at Object.<anonymous> (/usr/local/Cellar/passenger/6.0.7_2/libexec/src/nodejs_supportlib/vendor-copy/winston/lib/winston.js:84:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (/usr/local/Cellar/passenger/6.0.7_2/libexec/src/helper-scripts/node-loader.js:80:25)
```

**Comment by Kuzzy** [comment]
Hello, I have the same problem on startup!

**OS**: Ubuntu 16.04.5 LTS (no Docker or Kubernetes, just simple VM on DO )
**Passenger**: 6.0.10
**NodeJs**: 14.17.4



Log output:
```
(node:28015) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:674:11)
    at Object.get (internal/modules/cjs/loader.js:688:5)
    at Object.exports.setLevels (/usr/share/passenger/node/vendor-copy/winston/lib/winston/common.js:35:14)
    at Object.<anonymous> (/usr/share/passenger/node/vendor-copy/winston/lib/winston.js:84:8)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
```

If look into `usr/share/passenger/node/vendor-copy/winston/package.json` it's possible to see that it's 1.1.2 version of `winston` used, which is incompatible with `nodejs` v14+. Winston should be v3+ to work normally with `nodejs` v14+. I'm not sure how Passenger use `winston` and if it possible to just update this `winston` version to newer?
