### ISSUE TITLE
"daemon" directive is duplicate in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by scratchoo** [phusion/passenger-docker#354]
I am using the image phusion/passenger-ruby31:2.4.1 

creating and running a container on my localhost machine works fine, but when I deploy to production, I am getting the following in my log (the last lines keeps showing without stop)
```
*** Booting runit daemon...
*** Runit started as PID 2432
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
2022/12/25 17:51:10 [emerg] 340#340: "daemon" directive is duplicate in /etc/nginx/nginx.conf:4
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
ok: run: /etc/service/nginx-log-forwarder: (pid 2464) 0s
[ N 2022-12-25 17:51:42.5377 2469/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
[ N 2022-12-25 17:51:42.5554 2472/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-12-25 17:51:42.5562 2472/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-12-25 17:51:42.5664 2472/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 2472
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
[ N 2022-12-25 17:51:44.9728 2472/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
cron: can't lock /var/run/crond.pid, otherpid may be 248: Resource temporarily unavailable
```

The line 4 says: daemon" directive is duplicate in /etc/nginx/nginx.conf:4

Do you have any idea where does this comes from and how to solve it?

**Comment by CamJN** [comment]
Run `nginx -T` and post the output

**Comment by scratchoo** [comment]
Here is the output:

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
# configuration file /etc/nginx/nginx.conf:
user www-data;
worker_processes auto;
pid /run/nginx.pid;
daemon off;

include /etc/nginx/main.d/*.conf;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
#
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

# configuration file /etc/nginx/main.d/default.conf:
# By default, Nginx removes all environment variables inherited from its
# parent process, except for the TZ variable. This is documented at
# http://nginx.org/en/docs/ngx_core_module.html#env
# Because users usually want to inherit PATH, we allow it here
# explicitly.
env PATH;

# configuration file /etc/nginx/main.d/rails-env.conf:
env RAILS_ENV=production;
env RAILS_MASTER_KEY=22dee0b8a41537f7a0c123616ed5216c;
# configuration file /etc/nginx/modules-enabled/50-mod-http-image-filter.conf:
load_module modules/ngx_http_image_filter_module.so;

# configuration file /etc/nginx/modules-enabled/50-mod-http-passenger.conf:
load_module /usr/lib/nginx/modules/ngx_http_passenger_module.so;

# configuration file /etc/nginx/modules-enabled/50-mod-http-xslt-filter.conf:
load_module modules/ngx_http_xslt_filter_module.so;

# configuration file /etc/nginx/modules-enabled/50-mod-mail.conf:
load_module modules/ngx_mail_module.so;

# configuration file /etc/nginx/modules-enabled/50-mod-stream.conf:
load_module modules/ngx_stream_module.so;

# configuration file /etc/nginx/mime.types:

types {
    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/javascript                js;
    application/atom+xml                  atom;
    application/rss+xml                   rss;

    text/mathml                           mml;
    text/plain                            txt;
    text/vnd.sun.j2me.app-descriptor      jad;
    text/vnd.wap.wml                      wml;
    text/x-component                      htc;

    image/png                             png;
    image/tiff                            tif tiff;
    image/vnd.wap.wbmp                    wbmp;
    image/x-icon                          ico;
    image/x-jng                           jng;
    image/x-ms-bmp                        bmp;
    image/svg+xml                         svg svgz;
    image/webp                            webp;

    application/font-woff                 woff;
    application/java-archive              jar war ear;
    application/json                      json;
    application/mac-binhex40              hqx;
    application/msword                    doc;
    application/pdf                       pdf;
    application/postscript                ps eps ai;
    application/rtf                       rtf;
    application/vnd.apple.mpegurl         m3u8;
    application/vnd.ms-excel              xls;
    application/vnd.ms-fontobject         eot;
    application/vnd.ms-powerpoint         ppt;
    application/vnd.wap.wmlc              wmlc;
    application/vnd.google-earth.kml+xml  kml;
    application/vnd.google-earth.kmz      kmz;
    application/x-7z-compressed           7z;
    application/x-cocoa                   cco;
    application/x-java-archive-diff       jardiff;
    application/x-java-jnlp-file          jnlp;
    application/x-makeself                run;
    application/x-perl                    pl pm;
    application/x-pilot                   prc pdb;
    application/x-rar-compressed          rar;
    application/x-redhat-package-manager  rpm;
    application/x-sea                     sea;
    application/x-shockwave-flash         swf;
    application/x-stuffit                 sit;
    application/x-tcl                     tcl tk;
    application/x-x509-ca-cert            der pem crt;
    application/x-xpinstall               xpi;
    application/xhtml+xml                 xhtml;
    application/xspf+xml                  xspf;
    application/zip                       zip;

    application/octet-stream              bin exe dll;
    application/octet-stream              deb;
    application/octet-stream              dmg;
    application/octet-stream              iso img;
    application/octet-stream              msi msp msm;

    application/vnd.openxmlformats-officedocument.wordprocessingml.document    docx;
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet          xlsx;
    application/vnd.openxmlformats-officedocument.presentationml.presentation  pptx;

    audio/midi                            mid midi kar;
    audio/mpeg                            mp3;
    audio/ogg                             ogg;
    audio/x-m4a                           m4a;
    audio/x-realaudio                     ra;

    video/3gpp                            3gpp 3gp;
    video/mp2t                            ts;
    video/mp4                             mp4;
    video/mpeg                            mpeg mpg;
    video/quicktime                       mov;
    video/webm                            webm;
    video/x-flv                           flv;
    video/x-m4v                           m4v;
    video/x-mng                           mng;
    video/x-ms-asf                        asx asf;
    video/x-ms-wmv                        wmv;
    video/x-msvideo                       avi;
}

# configuration file /etc/nginx/conf.d/mod-http-passenger.conf:
### Begin automatically installed Phusion Passenger config snippet ###
passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby /usr/bin/passenger_free_ruby;

passenger_instance_registry_dir /var/run/passenger-instreg;

### End automatically installed Phusion Passenger config snippet ###

# configuration file /etc/nginx/sites-enabled/webapp.conf:
server {
    listen 80;
    root /home/app/webapp/public;

    # The following deploys your Ruby/Python/Node.js/Meteor app on Passenger.

    # Not familiar with Passenger, and used (G)Unicorn/Thin/Puma/pure Node before?
    # Yes, this is all you need to deploy on Passenger! All the reverse proxying,
    # socket setup, process management, etc are all taken care automatically for
    # you! Learn more at https://www.phusionpassenger.com/.
    passenger_enabled on;
    passenger_user app;

    # If this is a Ruby app, specify a Ruby version:
    # For Ruby 3.1
    passenger_ruby /usr/bin/ruby3.1;

    # Nginx has a default limit of 1 MB for request bodies, which also applies
    # to file uploads. The following line enables uploads of up to 50 MB:
    client_max_body_size 50M;
}
```

**Comment by scratchoo** [comment]
From answers online, people saying that the line "daemon off;" should be removed, and because that line is set within the image, I git rid of it using this at the end of my Dockerfile:

```
RUN sed -i '/daemon off;/d' /etc/nginx/nginx.conf
```

Doing this, the previous error seems not showing like before, but I have the following errors instead (the reason of them is because my hosting service (PaaS) is already exposing the port 80 with the container, and I think the image is also trying to bind that port?)

```
nginx: [emerg] still could not bind()
2022/12/26 15:28:26 [emerg] 2674#2674: still could not bind()
[ N 2022-12-26 15:27:45.4177 346/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-12-26 15:27:45.4355 346/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 346
[ N 2022-12-26 15:27:47.8394 346/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 2415 output: SpawnEnvSetupperShell: /root/.bash_profile: Permission denied
2022/12/26 15:28:26 [emerg] 2674#2674: bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:26 [emerg] 2674#2674: bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:26 [emerg] 2674#2674: bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:26 [emerg] 2674#2674: bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:26 [emerg] 2674#2674: bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:26 [emerg] 2674#2674: still could not bind()
ok: run: /etc/service/nginx-log-forwarder: (pid 2701) 1s
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:29 [emerg] 2699#2699: bind() to 0.0.0.0:80 failed (98: Address already in use)
cron: can't lock /var/run/crond.pid, otherpid may be 250: Resource temporarily unavailable
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:29 [emerg] 2699#2699: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:29 [emerg] 2699#2699: bind() to 0.0.0.0:80 failed (98: Address already in use)
cron: can't lock /var/run/crond.pid, otherpid may be 250: Resource temporarily unavailable
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:29 [emerg] 2699#2699: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2022/12/26 15:28:29 [emerg] 2699#2699: bind() to 0.0.0.0:80 failed (98: Address already in use)
cron: can't lock /var/run/crond.pid, otherpid may be 250: Resource temporarily unavailable
```

Please, advice how I can stop binding port 80 from my Dockerfile

**Comment by CamJN** [comment]
your hosting provider exposing port 80 is not the cause, ports inside the container and outside on the host are different and need to be mapped to each other by docker. What you're seeing is two (or more) things trying to bind port 80 in your container. also as for the nginx daemon directive, it was only in your nginx config once, so something very strange is happening here. Can you include your Dockerfile?

**Comment by scratchoo** [comment]
yes sure

```
FROM phusion/passenger-ruby31:2.4.1
# Set correct environment variables.
ENV HOME /root
ENV RAILS_ENV production

ARG ENV_FILE
COPY $ENV_FILE /etc/environment

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -q update && apt-get upgrade -y -o Dpkg::Options::="--force-confold" && \
    apt-get install -y sudo && \
    apt-get install -y tzdata && \
    apt-get install -y git && \
    apt-get install -y nano

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn

ENV DEBIAN_FRONTEND teletype

RUN rm -f /etc/service/nginx/down

# Remove the default site
RUN rm /etc/nginx/sites-enabled/default

# Add the nginx info
ADD ./nginx.conf /etc/nginx/sites-enabled/webapp.conf

# Add the rails-env configuration file so Nginx preserves the environment variables listed
ADD ./rails-env.conf /etc/nginx/main.d/rails-env.conf

RUN mkdir /home/app/webapp

#  - - - - - - - - - - This quick hack invalidates the cache - - - - - - - - - - 
ADD https://www.google.com /time.now

COPY git_clone_app.sh /home/app/
# git_clone_app.sh just contains a bash command "git clone some_remote_repo /home/app/webapp
RUN bash /home/app/git_clone_app.sh
RUN rm /home/app/git_clone_app.sh

WORKDIR /home/app/webapp/

RUN chown -R app:app /home/app/webapp

RUN mkdir -p /home/app/webapp/.bundle/ && \
    touch /home/app/webapp/.bundle/config && \
    chmod -R 777 /home/app/webapp/.bundle/config

RUN bundle update --bundler

RUN bundle config set --local without 'development test'
RUN sudo -u app bundle install

RUN sudo -u app  RAILS_ENV=production bundle exec rake assets:precompile

# remove node_modules folder after compiling assets
RUN rm -rf /home/app/webapp/node_modules

RUN mkdir -p /etc/my_init.d
ADD ./post_deploy.sh /etc/my_init.d/post_deploy.sh
RUN chmod +x /etc/my_init.d/*.sh

RUN apt-get -qy autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN sed -i '/daemon off;/d' /etc/nginx/nginx.conf
```

The nginx.conf file that I am copying to /etc/nginx/sites-enabled looks like this:
notice the line "listen 80"; if I changed it to something like 5000 or 8000 I was getting 0.0.0.5000 address already in use, so I comment it like you see to prevent it, but even with that I still get 0.0.0:80 address already in use

```
server {
    # listen 80;
    root /home/app/webapp/public;

    passenger_enabled on;
    passenger_user app;

    # If this is a Ruby app, specify a Ruby version:
    # For Ruby 3.1
    passenger_ruby /usr/bin/ruby3.1;

    # Nginx has a default limit of 1 MB for request bodies, which also applies
    # to file uploads. The following line enables uploads of up to 50 MB:
    client_max_body_size 50M;
}
```

the post_deploy.sh I  use in the Dockerfile, just contains

```
#!/bin/bash
cd /home/app/webapp

bundle exec rails db:create
bundle exec rails db:migrate
```

Forgive me for the mess, as I am new to docker, I must be doing something wrong, but also I noticed that the image I build is big (maybe) as every time I push it to the registry there is something like 628Mb + 110Mb gets pushed every single time. And on that specific hosting I use, it takes about 25min just to get deployed, compared to another image I built (for another stack which tooks only 5min to get deployed)

**Comment by scratchoo** [comment]
@CamJN  were you able to find anything related to this issue?

**Comment by CamJN** [comment]
- The image being large is expected, the passenger images are meant to be easy to use so they are not small images
- You probably shouldn't install sudo, just change the user that runs those command via the Dockerfile `USER` directive, then put it back to the root user after

I uncommented the listen line in nginx.conf:

```
  server {
    listen 80;
    root /home/app/webapp/public;

    passenger_enabled on;
    passenger_user app;

    # If this is a Ruby app, specify a Ruby version:
    # For Ruby 3.1
    passenger_ruby /usr/bin/ruby3.1;

    # Nginx has a default limit of 1 MB for request bodies, which also applies
    # to file uploads. The following line enables uploads of up to 50 MB:
    client_max_body_size 50M;
}
```

I built the following Dockerfile with `docker build . --build-arg ENV_FILE=enviro -t nginx_posts`:

```Dockerfile
FROM phusion/passenger-ruby31:2.4.1
# Set correct environment variables.
ENV HOME /root
ENV RAILS_ENV production

ARG ENV_FILE
COPY $ENV_FILE /etc/environment

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -q update && apt-get upgrade -y -o Dpkg::Options::="--force-confold" && \
    apt-get install -y sudo && \
    apt-get install -y tzdata && \
    apt-get install -y git && \
    apt-get install -y nano

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn

ENV DEBIAN_FRONTEND teletype

RUN rm -f /etc/service/nginx/down

# Remove the default site
RUN rm /etc/nginx/sites-enabled/default

# Add the nginx info
ADD ./nginx.conf /etc/nginx/sites-enabled/webapp.conf

# Add the rails-env configuration file so Nginx preserves the environment variables listed
ADD ./rails-env.conf /etc/nginx/main.d/rails-env.conf

#  - - - - - - - - - - This quick hack invalidates the cache - - - - - - - - - - 
ADD https://www.google.com /time.now

COPY git_clone_app.sh /home/app/
# git_clone_app.sh just contains a bash command "git clone some_remote_repo /home/app/webapp
USER app
RUN mkdir /home/app/webapp
RUN /home/app/git_clone_app.sh
RUN rm /home/app/git_clone_app.sh

WORKDIR /home/app/webapp/

RUN chown -R app:app /home/app/webapp

RUN mkdir -p /home/app/webapp/.bundle/ && \
    touch /home/app/webapp/.bundle/config && \
    chmod -R 777 /home/app/webapp/.bundle/config

RUN bundle update --bundler

RUN bundle config set --local without 'development test'

RUN bundle install
ENV RAILS_ENV=production
RUN bundle exec rake assets:precompile

# remove node_modules folder after compiling assets
RUN rm -rf /home/app/webapp/node_modules

USER root
RUN mkdir -p /etc/my_init.d
ADD ./post_deploy.sh /etc/my_init.d/post_deploy.sh
RUN chmod +x /etc/my_init.d/*.sh

RUN apt-get -qy autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

and then I ran the image with `docker run -it -p8181:80 nginx_posts` and got this output:

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Dec 30 20:05:45 dd540ad01306 syslog-ng[14]: syslog-ng starting up; version='3.25.1'
*** Running /etc/my_init.d/30_presetup_nginx.sh...
*** Running /etc/my_init.d/post_deploy.sh...
Created database 'db/production.sqlite3'
*** Booting runit daemon...
*** Runit started as PID 28
ok: run: /etc/service/nginx-log-forwarder: (pid 35) 0s
Dec 30 20:05:49 dd540ad01306 cron[33]: (CRON) INFO (pidfile fd = 3)
Dec 30 20:05:49 dd540ad01306 cron[33]: (CRON) INFO (Running @reboot jobs)
[ N 2022-12-30 20:05:49.0833 40/T1 age/Wat/WatchdogMain.cpp:1377 ]: Starting Passenger watchdog...
[ N 2022-12-30 20:05:49.1044 43/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-12-30 20:05:49.1046 43/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-12-30 20:05:49.1181 43/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 43
[ N 2022-12-30 20:05:52.2496 43/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
```


As you can see, nginx is not getting duplicate directives nor listening on already used ports. If you test running the image on your machine I'm guessing that you'll find the same, since docker is pretty consistent.

**Comment by CamJN** [comment]
So my best guess as to what is causing your issues is your host is doing something weird.

**Comment by scratchoo** [comment]
@CamJN I don't think it's a Sudo issue, by copying your suggested Dockerfile content I was getting a lot of issue (on my local machine) related to permission, like

```
Cloning into '/home/app/webapp'...
warning: unable to access '/root/.config/git/attributes': Permission denied
```

and errors like when trying to update bundler:

```
Step 25/35 : RUN bundle update --bundler
 ---> Running in 2a2bb6208ad0
`/root` is not writable.
```

and also when pre-compiling assets (I use esbuild and yarn)

```
Error: EACCES: permission denied, open '/root/.config/yarn'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at /usr/share/yarn/lib/cli.js:97395:58
    at Array.map (<anonymous>)
    at parseRcPaths (/usr/share/yarn/lib/cli.js:97393:78)
    at Object.findRc (/usr/share/yarn/lib/cli.js:97407:10)
    at getRcConfigForCwd (/usr/share/yarn/lib/cli.js:56965:74)
    at /usr/share/yarn/lib/cli.js:88756:56
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
rake aborted!
```

Without sudo, I am getting all these permission issues, not sure how you did to pass them, **but I think using sudo is necessary and isn't a bad thing?**

But regardless, I wanted to know if it's a Sudo problem, so I precompiled the assets manually before even building the image, and I commented out the lines that caused the permission errors etc, That way I was able to build the image without any use of sudo, and here is what happened:

I got the original messages I was getting (like what I wrote on my very first post) which is this:

```
cron: can't lock /var/run/crond.pid, otherpid may be 251: Resource temporarily unavailable
```
No difference from what I was getting when I used sudo, So I realized that the nginx "Address already in use" was the result of me removing the line "deamon off;" from /etc/nginx/nginx.conf (the last line In my Dockerfile)

That lead me to search if there is any existing issue with the baseimage-docker and I found this old issue: 

https://github.com/phusion/baseimage-docker/issues/115

The last comment there suggested to use:

```
service cron stop
```

I tried it via terminal on my running docker host and it solved the whole problem for me, no more repetitive messages ever.

I am happy that at least I found a solution, but I am still confused what's the source of it? and not sure if it's a hacky way to go via ssh every time after I deploy and type that command manually.

So yeah, I would like to hear your opinion (about "sudo" thing and this "cron" one too). Thanks

**Comment by CamJN** [comment]
`warning: unable to access '/root/.config/git/attributes': Permission denied` that looks like you have the `HOME` env var set to `/root/` in your environment file perhaps, or some similar var like `XDG_CONFIG_HOME` or something? The env is normally set correctly by docker when you use the `USER` directive, so the `app` user would not access `/root/`, which was the case for me since I did not have access to your environment file.

The reason I suggest against using sudo for changing users is simply that you shouldn't need to, and it leaves sudo around in your image afterwards.

> So I realized that the nginx "Address already in use" was the result of me removing the line "deamon off;" from /etc/nginx/nginx.conf

That makes sense, the startup code expects nginx to stay in the foreground and likely started it up multiple times when nginx forked off into a daemon in the background, assuming it had died.

Which leaves the cron thing. Can you ssh into a running container that hasn't had cron disabled and check the output of `ps -aux`, as well as the contents of `/var/run/crond.pid`? I didn't get any issues with cron when I ran my image but the env vars could be causing a difference here too.

**Comment by scratchoo** [comment]
ps -aux

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  2.6  0.5 104928 12032 ?        Ss   22:39   0:02 init -z       
root         111  0.2  0.5  35736 11748 ?        Ss   22:40   0:00 /lib/systemd/systemd-journald
root         223  0.0  0.2  20240  4680 ?        Ss   22:40   0:00 /lib/systemd/systemd-udevd
root         241  0.0  0.1   9716  2788 ?        Ss   22:40   0:00 /usr/sbin/cron -f
message+     242  0.2  0.2   7132  4232 ?        Ss   22:40   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root         254  0.0  0.1 154396  3640 ?        Ssl  22:40   0:00 /usr/sbin/rsyslogd -n -iNONE
root         265  0.1  0.3  17120  6336 ?        Ss   22:40   0:00 /lib/systemd/systemd-logind
systemd+     269  0.0  0.3  19056  6580 ?        Ss   22:40   0:00 /lib/systemd/systemd-networkd
root         295  0.0  0.1  21648  2848 ?        Ss   22:40   0:00 /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
root         297  0.0  0.0  21648  1056 ?        S    22:40   0:00 /usr/sbin/saslauthd -a pam -c -m /var/run/saslauthd -n 2
systemd+     322  0.0  0.5  24460 12192 ?        Ss   22:40   0:00 /lib/systemd/systemd-resolved
root         703  0.0  0.1   7920  2104 ?        Ss   22:40   0:00 /usr/sbin/xinetd -pidfile /run/xinetd.pid -stayalive -inetd_compat -inetd_ipv6
root         971  0.0  0.1   8500  2200 ?        Ss+  22:40   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
root         972  0.0  0.0   2624  1684 ?        Ss+  22:40   0:00 /sbin/agetty -o -p -- \u --noclear tty2 linux
root         988  0.0  0.7 284988 16012 ?        Ssl  22:40   0:00 /usr/lib/packagekit/packagekitd
root         993  0.0  0.4 236416  8956 ?        Ssl  22:40   0:00 /usr/lib/policykit-1/polkitd --no-debug
root        2288  0.0  0.3  12168  6984 ?        Ss   22:40   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        2361  0.0  0.1  10136  2276 ?        S    22:40   0:00 /bin/bash /usr/sbin/jelinit start
root        2363  0.0  0.0   3776  1788 ?        S    22:40   0:00 /usr/bin/launcher -l /var/log/run.log -u root -e /.jelenv -w /home/app/webapp -- /sbin/my_init
root        2365  0.1  0.5  20440 11236 ?        S    22:40   0:00 /usr/bin/python3 -u /sbin/my_init
root        2390  0.0  0.3 233852  7808 ?        S    22:40   0:00 /usr/sbin/syslog-ng --pidfile /var/run/syslog-ng.pid -F --no-caps
root        2445  0.0  0.0   2516   720 ?        S    22:40   0:00 /usr/bin/runsvdir -P /etc/service
root        2446  0.0  0.0   2364   720 ?        Ss   22:40   0:00 runsv nginx
root        2447  0.0  0.0   2364  1248 ?        Ss   22:40   0:00 runsv cron
root        2448  0.0  0.0   2364   724 ?        Ss   22:40   0:00 runsv nginx-log-forwarder
root        2449  0.0  0.0   2364   724 ?        Ss   22:40   0:00 runsv sshd
root        2451  0.0  0.6  55056 13088 ?        S    22:40   0:00 nginx: master process /usr/sbin/nginx
root        2457  0.0  0.7 303044 15348 ?        Ssl  22:40   0:00 Passenger watchdog
root        2460  0.1  0.9 1216684 19836 ?       Sl   22:40   0:00 Passenger core
www-data    2481  0.0  0.1  55232  3296 ?        S    22:40   0:00 nginx: worker process
www-data    2482  0.0  0.1  55232  3296 ?        S    22:40   0:00 nginx: worker process
www-data    2483  0.0  0.1  55232  3296 ?        S    22:40   0:00 nginx: worker process
www-data    2484  0.0  0.1  55232  3296 ?        S    22:40   0:00 nginx: worker process
root        2494  0.0  0.0   8412   576 ?        S    22:40   0:00 tail -F /var/log/nginx/error.log
root        2643  0.0  0.3  12280  7276 ?        Ss   22:41   0:00 sshd: root@pts/0
root        2649  0.5  0.3  13432  7192 pts/0    Ss   22:41   0:00 -bash
root        2819  0.0  0.1  11788  3252 pts/0    R+   22:41   0:00 ps -aux
```

and

```
 cat /var/run/crond.pid
241
```
where in log.run (host) is saying:

```
cron: can't lock /var/run/crond.pid, otherpid may be 241: Resource temporarily unavailable
```

For the env variables, I only have this:

```
RAILS_ENV=production
RAILS_MASTER_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxx
```
At the beginning of Dockerfile, there is a line where I set HOME:

```
FROM phusion/passenger-ruby31:2.4.1
ENV HOME /root
```
By using using "setuser app" as suggested here: https://github.com/phusion/passenger-docker/issues/110#issuecomment-148680727 I was able to get rid of permission errors

**Comment by CamJN** [comment]
That is weird, it's like something is running cron after it has already been started. my_init starts cron so nothing else should need to, is it possible that your app tries to start cron for a job server like active job or something?

**Comment by scratchoo** [comment]
@CamJN not at all, I did an experiment by building a docker image that is not passenger-ruby and I find it to be working for me with the same code and no issue.

BTW I have an issue with nginx & passenger that I don't understand

if I run
```
CMD passenger start --port 3000
```

I can bind the port (for example 5000 to 3000) and I am able to get the app working (the requests go directly to passenger) everything is fine.

But I want to make the request go to passenger **through nginx**, so I try this:

```
CMD service nginx start --port 80 && passenger start --port 3000
```

Then I run the container by binding port **5000:80** and I visit localhost:5000 I get the passenger error page saying "We're sorry, but something went wrong." which I think it's a good sign that the request is going through nginx, when I see the log the issue looks like this:

```
App 176 output: Error: The application encountered the following error: Could not find rails-7.0.4, sprockets-rails-3.4.2, pg-1.4.3, puma-5.6.5, jsbundling-rails-1.0.3, turbo-rails-1.3.0, stimulus-rails-1.1.0, jbuilder-2.11.5, devise-4.8.1, devise-bootstrap-views-1.1.0, rails-i18n-7.0.5, devise-i18n-1.10.2, kaminari-1.2.2, bootstrap5-kaminari-views-0.0.1, bootsnap-1.13.0, debug-1.6.2, web-console-4.2.0, capybara-3.37.1, selenium-webdriver-4.5.0, webdrivers-5.2.0, actioncable-7.0.4, actionmailbox-7.0.4, actionmailer-7.0.4, actionpack-7.0.4, actiontext-7.0.4, actionview-7.0.4, activejob-7.0.4, activemodel-7.0.4, activerecord-7.0.4, activestorage-7.0.4, activesupport-7.0.4, railties-7.0.4, sprockets-4.1.1, nio4r-2.5.8, bcrypt-3.1.18, orm_adapter-0.5.0, responders-3.0.1, warden-1.2.9, i18n-1.12.0, kaminari-actionview-1.2.2, kaminari-activerecord-1.2.2, kaminari-core-1.2.2, msgpack-1.6.0, irb-1.4.1, reline-0.3.1, bindex-0.8.1.......
```

It seems that's it cannot find the installed gems, even if log in to the container and I try **rails -v** I get "rails: command not found" but if I run "bundle exec rails -v" I can get the rails version.
 
I would appreciate your help with this as I am try to run a docker image in the production with nginx+passenger for weeks and I failed every single time.

**Comment by CamJN** [comment]
If you are using nginx you don't start passenger manually with `passenger start` nginx starts it for you. The error you are seeing implies that when nginx starts passenger it is not running it with the environment that it gets when you run passenger manually. 

Make sure the `passenger_ruby` nginx config is set correctly (run `passenger-config about ruby-command` to help figure this out), and that the shell config files of the user that owns the app are not exiting before setting up the needed environment when run non-interactively (many shell rc files use a block like the following to bail early if run non-interactively).

```
if [[  ! ( $- =~ "i" ) ]]; then
    return 0
fi
```

Anything after such a block doesn't get setup when passenger tries to start your app.
