### ISSUE TITLE
irb/rails console RC file error

### ISSUE THREAD

**Issue by LocoDelAssembly** [phusion/passenger-docker#393]
I've noticed that since ruby33 release invoking "bundle exec irb" or "bundle exec rails c" causes this error:
```
$ bundle exec irb
Error loading RC file '/usr/local/rvm/rubies/ruby-3.3.0/.irbrc':
/usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- /home/app/irbrc (LoadError)
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/rvm/rubies/ruby-3.3.0/.irbrc:9:in `<top (required)>'
.
.
.
```

Is this a bug? Any advice on how to make this error stop? Both, `irb` and `rails c` seem to work fine despite this, but would be nicer if no errors occur.

Thanks

Last Good version:
```
$ echo "exit" | docker run --rm phusion/passenger-ruby32:latest bash -c "bundle init; bundle exec irb" 
Writing new Gemfile to //Gemfile
Switch to inspect mode.

```

Current version:
```
$ echo "exit" | docker run --rm phusion/passenger-ruby33:latest bash -c "bundle init; bundle exec irb"
Writing new Gemfile to //Gemfile
Error loading RC file '/usr/local/rvm/rubies/ruby-3.3.0/.irbrc':
/usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- /root/irbrc (LoadError)
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/rvm/rubies/ruby-3.3.0/.irbrc:9:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb/init.rb:399:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb/init.rb:399:in `run_config'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb/init.rb:49:in `setup'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb.rb:896:in `start'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/irb-1.11.0/exe/irb:9:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/irb:25:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/irb:25:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/bundle:25:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/bundle:25:in `<main>'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'
Switch to inspect mode.
```

Also happens with full version:
```
$ echo "exit" | docker run --rm phusion/passenger-full:latest bash -c "bundle init; bundle exec irb"
Writing new Gemfile to //Gemfile
Error loading RC file '/usr/local/rvm/rubies/ruby-3.3.0/.irbrc':
/usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- /root/irbrc (LoadError)
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /usr/local/rvm/rubies/ruby-3.3.0/.irbrc:9:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb/init.rb:399:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb/init.rb:399:in `run_config'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb/init.rb:49:in `setup'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/irb.rb:896:in `start'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/irb-1.11.0/exe/irb:9:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/irb:25:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/irb:25:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:28:in `block in <top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.5.3/exe/bundle:20:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/bundle:25:in `load'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/bundle:25:in `<main>'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
	from /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'
Switch to inspect mode.
```

**Comment by CamJN** [comment]
As a workaround, you can create a `/home/app/irbrc` file in your Dockerfile, I'll add one to the images in the next update.

**Comment by LocoDelAssembly** [comment]
If you mean ` echo "exit" | docker run -u9999 --rm test bash -c "cd /home/app; bundle init; bundle exec irb"`, it also fails with differerent path (`/home/app/irbrc`, you may see that above).

This is the Dockefile used:
```dockerfile
FROM phusion/passenger-ruby33:latest

RUN touch /home/app/irbrc
RUN touch /home/app/.irbrc
RUN touch /root/irbrc
RUN touch /root/.irbrc
RUN touch /usr/local/rvm/rubies/ruby-3.3.0/.irbrc
RUN touch /usr/local/rvm/rubies/ruby-3.3.0/irbrc
```

**Comment by CamJN** [comment]
My apologies for missing that you ran the test as the app user too. I've done more digging, and while i don't have a solution yet i did notice that the issue is the new version of irb included with ruby 3.3, you can replicate the problem in the `phusion/passenger-ruby32:latest` image by installing the latest irb:
```
root@5682e16462c2:/# bundle add irb
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...                
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...                
Fetching stringio 3.1.0                  
Fetching io-console 0.7.2                
Installing stringio 3.1.0 with native extensions
Installing io-console 0.7.2 with native extensions
Fetching psych 5.1.2
Installing psych 5.1.2 with native extensions
Fetching reline 0.5.0
Installing reline 0.5.0
Fetching rdoc 6.6.3.1
Installing rdoc 6.6.3.1
Fetching irb 1.12.0
Installing irb 1.12.0
root@5682e16462c2:/# bundle exec irb
Error loading RC file '/usr/local/rvm/rubies/ruby-3.2.3/.irbrc':
<internal:/usr/local/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- /root/irbrc (LoadError)
	from <internal:/usr/local/rvm/rubies/ruby-3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/rvm/rubies/ruby-3.2.3/.irbrc:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-3.2.3/gems/irb-1.12.0/lib/irb/init.rb:401:in `load'
	from /usr/local/rvm/gems/ruby-3.2.3/gems/irb-1.12.0/lib/irb/init.rb:401:in `block in run_config'
	from /usr/local/rvm/gems/ruby-3.2.3/gems/irb-1.12.0/lib/irb/init.rb:398:in `each'
	from /usr/local/rvm/gems/ruby-3.2.3/gems/irb-1.12.0/lib/irb/init.rb:398:in `run_config'
	from /usr/local/rvm/gems/ruby-3.2.3/gems/irb-1.12.0/lib/irb/init.rb:54:in `setup'
	from /usr/local/rvm/gems/ruby-3.2.3/gems/irb-1.12.0/lib/irb.rb:877:in `start'
	from /usr/local/rvm/gems/ruby-3.2.3/gems/irb-1.12.0/exe/irb:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-3.2.3/bin/irb:25:in `load'
	from /usr/local/rvm/gems/ruby-3.2.3/bin/irb:25:in `<main>'
	from /usr/local/rvm/gems/ruby-3.2.3/bin/ruby_executable_hooks:22:in `eval'
	from /usr/local/rvm/gems/ruby-3.2.3/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by CamJN** [comment]
The change appears deliberate: https://github.com/ruby/irb/pull/817

So rvm's `.irbrc` file is not compatible with `irb 1.11.0`.

Still not sure why it can't load the file even if it exists and has correct permissions.

**Comment by CamJN** [comment]
It's because require expects an `.rb` extension and `irbrc` doesn't have one. `rvm` should probably use `load` instead.

**Comment by CamJN** [comment]
I've filed https://github.com/rvm/rvm/issues/5449 to get this fixed upstream. in the meantime changing rvm's `/usr/local/rvm/rubies/ruby-3.2.3/.irbrc` to use `load` instead of `require` worked for me.

**Comment by LocoDelAssembly** [comment]
Perfect, thanks @CamJN!

**Comment by LocoDelAssembly** [comment]
Just reminding this issue still persists, no activity occurred at https://github.com/rvm/rvm/issues/5449

**Comment by CamJN** [comment]
Yes, it hasn't been fixed in rvm, so it continues to be a problem. This is the wrong repo to pester to get rvm to fix their issue.

**Comment by LocoDelAssembly** [comment]
Understood, but maybe something can be done on this side?  I was unable to install ruby 3.3.0 when testing, but with following Dockerfile using 3.3.4 I'm unable to reproduce the problem. 

```
$ cat Dockerfile
FROM ubuntu:24.04

RUN apt update && apt install -y gpg curl

RUN gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

RUN curl -sSL https://get.rvm.io | bash -s stable

RUN /bin/bash -l -c "rvm install 3.3.4"

RUN useradd -m -s /bin/bash app

ENTRYPOINT ["/bin/bash", "-l"]
```
```
$ docker build -t rvm-test .
[+] Building 0.1s (10/10) FINISHED                                                                                                                            docker:default
 => [internal] load build definition from Dockerfile                                                                                                                    0.0s
 => => transferring dockerfile: 393B                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:24.04                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                         0.0s
 => [1/6] FROM docker.io/library/ubuntu:24.04                                                                                                                           0.0s
 => CACHED [2/6] RUN apt update && apt install -y gpg curl                                                                                                              0.0s
 => CACHED [3/6] RUN gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB                 0.0s
 => CACHED [4/6] RUN curl -sSL https://get.rvm.io | bash -s stable                                                                                                      0.0s
 => CACHED [5/6] RUN /bin/bash -l -c "rvm install 3.3.4"                                                                                                                0.0s
 => CACHED [6/6] RUN useradd -m -s /bin/bash app                                                                                                                        0.0s
 => exporting to image                                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                 0.0s
 => => writing image sha256:dcd246d4787883b46e23da40db36c6cb6d1fed16e8a168cde7a44879d58b4d34                                                                            0.0s
 => => naming to docker.io/library/rvm-test                                                                                                                             0.0s
```
```
$ docker run -it --rm rvm-test
root@989093ba29ca:/# cd
root@989093ba29ca:~# bundle init
Writing new Gemfile to /root/Gemfile
root@989093ba29ca:~# bundle exec irb
3.3.4 :001 > exit
root@989093ba29ca:~# su app -l
app@989093ba29ca:~$ bundle init
Writing new Gemfile to /home/app/Gemfile
app@989093ba29ca:~$ bundle exec irb
3.3.4 :001 > exit
app@989093ba29ca:~$ 
```

**Comment by CamJN** [comment]
This seems to be fixed in the latest image tag.

**Comment by mathieujobin** [comment]
@LocoDelAssembly Note that rvm "stable" is 3 years old, and master is now recommended...
