### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hopewise** [phusion/passenger-docker#394]
Hello

I have built an image using `FROM phusion/passenger-ruby33:latest` that I am running in `aarch64`
However, I am getting error when I `ruby -version`

```
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [aarch64-linux]
/usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems.rb:165: [BUG] Segmentation fault at 0xffffffffffffffff
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [aarch64-linux]

-- Control frame information -----------------------------------------------
c:0005 p:0074 s:0023 e:000021 CLASS  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems.rb:165
c:0004 p:0045 s:0019 e:000018 TOP    /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems.rb:115 [FINISH]
c:0003 p:---- s:0012 e:000011 CFUNC  :require
c:0002 p:0012 s:0007 e:000006 TOP    <internal:gem_prelude>:2 [FINISH]
c:0001 p:0000 s:0003 E:001f40 DUMMY  [FINISH]

-- Ruby level backtrace information ----------------------------------------
<internal:gem_prelude>:2:in `<internal:gem_prelude>'
<internal:gem_prelude>:2:in `require'
/usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems.rb:115:in `<top (required)>'
/usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems.rb:165:in `<module:Gem>'

-- Threading information ---------------------------------------------------
Total ractor count: 1
Ruby thread count for this ractor: 1

-- Machine register context ------------------------------------------------
  x0: 0xffffffffffffffff  x1: 0x000000000000c2e3  x2: 0x0000ffff95b7f439
  x3: 0x0000000000000000  x4: 0xffffffffffffffff  x5: 0x0000000000000018
  x6: 0x0000000000000000  x7: 0x0000aaaafb9ecbd0 x18: 0x0000000000000000
 x19: 0x0000ffff95b7f438 x20: 0x0000ffff95b7f050 x21: 0x0000ffff95b7f5a0
 x22: 0x0000ffff95b37280 x23: 0x0000ffff98031000 x24: 0x0000000000000001
 x25: 0x0000aaaafb9e9ba8 x26: 0xffffffff00000000 x27: 0x0000ffff970fbef8
 x28: 0x0000ffff95b37280 x29: 0x0000ffffd3cebd00  sp: 0x0000ffffd3cebd00
 fau: 0xffffffffffffffff

-- C level backtrace information -------------------------------------------
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_print_backtrace+0x14) [0xffff97d59e10] /usr/local/rvm/src/ruby-3.3.0/vm_dump.c:820
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_vm_bugreport) /usr/local/rvm/src/ruby-3.3.0/vm_dump.c:1151
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_bug_for_fatal_signal+0xe8) [0xffff97b5d6d8] /usr/local/rvm/src/ruby-3.3.0/error.c:1065
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(sigsegv+0x5c) [0xffff97ca9d8c] /usr/local/rvm/src/ruby-3.3.0/signal.c:926
linux-vdso.so.1(__kernel_rt_sigreturn+0x0) [0xffff98086668]
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_new+0x34) [0xffff97ca6814] /usr/local/rvm/src/ruby-3.3.0/shape.c:148
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_insert_aux) /usr/local/rvm/src/ruby-3.3.0/shape.c:247
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_insert+0x10) [0xffff97ca69f8] /usr/local/rvm/src/ruby-3.3.0/shape.c:287
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors) /usr/local/rvm/src/ruby-3.3.0/shape.c:434
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors+0x14) [0xffff97ca6a2c] /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors) /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors+0x14) [0xffff97ca6a2c] /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors) /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors+0x14) [0xffff97ca6a2c] /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors) /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors+0x14) [0xffff97ca6a2c] /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors) /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors+0x14) [0xffff97ca6a2c] /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(redblack_cache_ancestors) /usr/local/rvm/src/ruby-3.3.0/shape.c:431
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_shape_alloc_new_child+0x8) [0xffff97ca797c] /usr/local/rvm/src/ruby-3.3.0/shape.c:473
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(get_next_shape_internal) /usr/local/rvm/src/ruby-3.3.0/shape.c:529
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_shape_get_next) /usr/local/rvm/src/ruby-3.3.0/shape.c:721
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(general_ivar_set+0x4c) [0xffff97d229d0] /usr/local/rvm/src/ruby-3.3.0/variable.c:1513
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_class_ivar_set) /usr/local/rvm/src/ruby-3.3.0/variable.c:4236
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_ivar_set+0x94) [0xffff97d22bc4] /usr/local/rvm/src/ruby-3.3.0/variable.c:1844
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(vm_exec_core+0x2620) [0xffff97d3fd80] /usr/local/rvm/src/ruby-3.3.0/vm_insnhelper.c:1639
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_vm_exec+0x1c0) [0xffff97d43910] /usr/local/rvm/src/ruby-3.3.0/vm.c:2486
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(load_iseq_eval+0x34) [0xffff97bcdfe4] /usr/local/rvm/src/ruby-3.3.0/load.c:774
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(require_internal) /usr/local/rvm/src/ruby-3.3.0/load.c:1281
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_require_string_internal+0x28) [0xffff97bcecc8] /usr/local/rvm/src/ruby-3.3.0/load.c:1380
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_require_string) /usr/local/rvm/src/ruby-3.3.0/load.c:1373
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(vm_call_cfunc_with_frame_+0x9c) [0xffff97d2d3cc] /usr/local/rvm/src/ruby-3.3.0/vm_insnhelper.c:3490
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(vm_call_cfunc_with_frame) /usr/local/rvm/src/ruby-3.3.0/vm_insnhelper.c:3518
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(vm_call_cfunc_other) /usr/local/rvm/src/ruby-3.3.0/vm_insnhelper.c:3544
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(vm_sendish+0x74) [0xffff97d3d880] /usr/local/rvm/src/ruby-3.3.0/vm_insnhelper.c:5581
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(vm_exec_core) /usr/local/rvm/src/ruby-3.3.0/insns.def:834
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(rb_vm_exec+0x1c0) [0xffff97d43910] /usr/local/rvm/src/ruby-3.3.0/vm.c:2486
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(ruby_init_prelude+0x4) [0xffff97ca2f60] /usr/local/rvm/src/ruby-3.3.0/ruby.c:1730
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(ruby_opt_init) /usr/local/rvm/src/ruby-3.3.0/ruby.c:1791
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(ruby_opt_init+0x14) [0xffff97ca44e8] /usr/local/rvm/src/ruby-3.3.0/ruby.c:1749
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(process_options) /usr/local/rvm/src/ruby-3.3.0/ruby.c:2284
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(ruby_process_options+0x164) [0xffff97ca5288] /usr/local/rvm/src/ruby-3.3.0/ruby.c:3014
/usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3(ruby_options+0xe0) [0xffff97b685e4] /usr/local/rvm/src/ruby-3.3.0/eval.c:121
/usr/local/rvm/rubies/ruby-3.3.0/bin/ruby(rb_main+0x14) [0xaaaacbd76b28] ./main.c:39
/usr/local/rvm/rubies/ruby-3.3.0/bin/ruby(main) ./main.c:58
[0xffff977173fc]
[0xffff977174cc]
[0xaaaacbd76bb0]

-- Other runtime information -----------------------------------------------

* Loaded script: ruby

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 fiber.so
    3 rational.so
    4 complex.so
    5 ruby2_keywords.rb
    6 /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/encdb.so
    7 /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/trans/transdb.so
    8 /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/rbconfig.rb
    9 /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/compatibility.rb
   10 /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/defaults.rb
   11 /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/deprecate.rb
   12 /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/errors.rb

* Process memory map:

aaaacbd76000-aaaacbd77000 r-xp 00000000 103:01 55635748                  /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby
aaaacbd87000-aaaacbd88000 r--p 00001000 103:01 55635748                  /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby
aaaacbd88000-aaaacbd89000 rw-p 00002000 103:01 55635748                  /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby
aaaafb7dc000-aaaafbb0e000 rw-p 00000000 00:00 0                          [heap]
ffff90f6e000-ffff926a4000 rw-p 00000000 00:00 0
ffff926a4000-ffff939f0000 r--s 00000000 103:01 11617338                  /usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3.0
ffff939f0000-ffff93a00000 rw-p 00000000 00:00 0
ffff93a03000-ffff93b20000 rw-p 00000000 00:00 0
ffff93bb0000-ffff93bc0000 rw-p 00000000 00:00 0
ffff93bfa000-ffff93c30000 r--s 00000000 103:01 55635748                  /usr/local/rvm/rubies/ruby-3.3.0/bin/ruby
ffff93c30000-ffff93c80000 rw-p 00000000 00:00 0
ffff93c80000-ffff93c82000 r-xp 00000000 103:01 19979805                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/trans/transdb.so
ffff93c82000-ffff93c92000 ---p 00002000 103:01 19979805                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/trans/transdb.so
ffff93c92000-ffff93c93000 r--p 00002000 103:01 19979805                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/trans/transdb.so
ffff93c93000-ffff93c94000 rw-p 00003000 103:01 19979805                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/trans/transdb.so
ffff93ca0000-ffff93cb0000 rw-p 00000000 00:00 0
ffff93cb0000-ffff93cb2000 r-xp 00000000 103:01 18968624                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/encdb.so
ffff93cb2000-ffff93cc1000 ---p 00002000 103:01 18968624                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/encdb.so
ffff93cc1000-ffff93cc2000 r--p 00001000 103:01 18968624                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/encdb.so
ffff93cc2000-ffff93cc3000 rw-p 00002000 103:01 18968624                  /usr/local/rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/aarch64-linux/enc/encdb.so
ffff93cd0000-ffff93cd1000 ---p 00000000 00:00 0
ffff93cd1000-ffff93d72000 rw-p 00000000 00:00 0
ffff93d72000-ffff93d73000 ---p 00000000 00:00 0
ffff93d73000-ffff93e14000 rw-p 00000000 00:00 0
ffff93e14000-ffff93e15000 ---p 00000000 00:00 0
ffff93e15000-ffff93eb6000 rw-p 00000000 00:00 0
ffff93eb6000-ffff93eb7000 ---p 00000000 00:00 0
ffff93eb7000-ffff93f58000 rw-p 00000000 00:00 0
ffff93f58000-ffff93f59000 ---p 00000000 00:00 0
ffff93f59000-ffff93ffa000 rw-p 00000000 00:00 0
ffff93ffa000-ffff93ffb000 ---p 00000000 00:00 0
ffff93ffb000-ffff9409c000 rw-p 00000000 00:00 0
ffff9409c000-ffff9409d000 ---p 00000000 00:00 0
ffff9409d000-ffff9413e000 rw-p 00000000 00:00 0
ffff9413e000-ffff9413f000 ---p 00000000 00:00 0
ffff9413f000-ffff941e0000 rw-p 00000000 00:00 0
ffff941e0000-ffff941e1000 ---p 00000000 00:00 0
ffff941e1000-ffff94282000 rw-p 00000000 00:00 0
ffff94282000-ffff94283000 ---p 00000000 00:00 0
ffff94283000-ffff94324000 rw-p 00000000 00:00 0
ffff94324000-ffff94325000 ---p 00000000 00:00 0
ffff94325000-ffff943c6000 rw-p 00000000 00:00 0
ffff943c6000-ffff943c7000 ---p 00000000 00:00 0
ffff943c7000-ffff94468000 rw-p 00000000 00:00 0
ffff94468000-ffff94469000 ---p 00000000 00:00 0
ffff94469000-ffff9450a000 rw-p 00000000 00:00 0
ffff9450a000-ffff9450b000 ---p 00000000 00:00 0
ffff9450b000-ffff945ac000 rw-p 00000000 00:00 0
ffff945ac000-ffff945ad000 ---p 00000000 00:00 0
ffff945ad000-ffff9464e000 rw-p 00000000 00:00 0
ffff9464e000-ffff9464f000 ---p 00000000 00:00 0
ffff9464f000-ffff946f0000 rw-p 00000000 00:00 0
ffff946f0000-ffff946f1000 ---p 00000000 00:00 0
ffff946f1000-ffff94792000 rw-p 00000000 00:00 0
ffff94792000-ffff94793000 ---p 00000000 00:00 0
ffff94793000-ffff94834000 rw-p 00000000 00:00 0
ffff94834000-ffff94835000 ---p 00000000 00:00 0
ffff94835000-ffff948d6000 rw-p 00000000 00:00 0
ffff948d6000-ffff948d7000 ---p 00000000 00:00 0
ffff948d7000-ffff94978000 rw-p 00000000 00:00 0
ffff94978000-ffff94979000 ---p 00000000 00:00 0
ffff94979000-ffff94a1a000 rw-p 00000000 00:00 0
ffff94a1a000-ffff94a1b000 ---p 00000000 00:00 0
ffff94a1b000-ffff94abc000 rw-p 00000000 00:00 0
ffff94abc000-ffff94abd000 ---p 00000000 00:00 0
ffff94abd000-ffff94b5e000 rw-p 00000000 00:00 0
ffff94b5e000-ffff94b5f000 ---p 00000000 00:00 0
ffff94b5f000-ffff94c00000 rw-p 00000000 00:00 0
ffff94c00000-ffff94c01000 ---p 00000000 00:00 0
ffff94c01000-ffff94ca2000 rw-p 00000000 00:00 0
ffff94ca2000-ffff94ca3000 ---p 00000000 00:00 0
ffff94ca3000-ffff94d44000 rw-p 00000000 00:00 0
ffff94d44000-ffff94d45000 ---p 00000000 00:00 0
ffff94d45000-ffff94de6000 rw-p 00000000 00:00 0
ffff94de6000-ffff94de7000 ---p 00000000 00:00 0
ffff94de7000-ffff94e88000 rw-p 00000000 00:00 0
ffff94e88000-ffff94e89000 ---p 00000000 00:00 0
ffff94e89000-ffff94f2a000 rw-p 00000000 00:00 0
ffff94f2a000-ffff94f2b000 ---p 00000000 00:00 0
ffff94f2b000-ffff94fcc000 rw-p 00000000 00:00 0
ffff94fcc000-ffff94fcd000 ---p 00000000 00:00 0
ffff94fcd000-ffff9506e000 rw-p 00000000 00:00 0
ffff9506e000-ffff9506f000 ---p 00000000 00:00 0
ffff9506f000-ffff95110000 rw-p 00000000 00:00 0
ffff95110000-ffff95120000 ---p 00000000 00:00 0
ffff95120000-ffff95b70000 rw-p 00000000 00:00 0
ffff95b7f000-ffff96ff0000 rw-p 00000000 00:00 0
ffff96ffc000-ffff970fd000 rw-p 00000000 00:00 0
ffff970fd000-ffff976c0000 r--p 00000000 103:01 4234387                   /usr/lib/locale/locale-archive
ffff976c0000-ffff976d4000 r-xp 00000000 103:01 45140193                  /usr/lib/aarch64-linux-gnu/libgcc_s.so.1
ffff976d4000-ffff976e3000 ---p 00014000 103:01 45140193                  /usr/lib/aarch64-linux-gnu/libgcc_s.so.1
ffff976e3000-ffff976e4000 r--p 00013000 103:01 45140193                  /usr/lib/aarch64-linux-gnu/libgcc_s.so.1
ffff976e4000-ffff976e5000 rw-p 00014000 103:01 45140193                  /usr/lib/aarch64-linux-gnu/libgcc_s.so.1
ffff976f0000-ffff97878000 r-xp 00000000 103:01 45140158                  /usr/lib/aarch64-linux-gnu/libc.so.6
ffff97878000-ffff97887000 ---p 00188000 103:01 45140158                  /usr/lib/aarch64-linux-gnu/libc.so.6
ffff97887000-ffff9788b000 r--p 00187000 103:01 45140158                  /usr/lib/aarch64-linux-gnu/libc.so.6
ffff9788b000-ffff9788d000 rw-p 0018b000 103:01 45140158                  /usr/lib/aarch64-linux-gnu/libc.so.6
ffff9788d000-ffff97899000 rw-p 00000000 00:00 0
ffff978a0000-ffff97926000 r-xp 00000000 103:01 45140247                  /usr/lib/aarch64-linux-gnu/libm.so.6
ffff97926000-ffff97935000 ---p 00086000 103:01 45140247                  /usr/lib/aarch64-linux-gnu/libm.so.6
ffff97935000-ffff97936000 r--p 00085000 103:01 45140247                  /usr/lib/aarch64-linux-gnu/libm.so.6
ffff97936000-ffff97937000 rw-p 00086000 103:01 45140247                  /usr/lib/aarch64-linux-gnu/libm.so.6
ffff97940000-ffff9796d000 r-xp 00000000 103:01 12836568                  /usr/lib/aarch64-linux-gnu/libcrypt.so.1.1.0
ffff9796d000-ffff9797c000 ---p 0002d000 103:01 12836568                  /usr/lib/aarch64-linux-gnu/libcrypt.so.1.1.0
ffff9797c000-ffff9797d000 r--p 0002c000 103:01 12836568                  /usr/lib/aarch64-linux-gnu/libcrypt.so.1.1.0
ffff9797d000-ffff9797e000 rw-p 0002d000 103:01 12836568                  /usr/lib/aarch64-linux-gnu/libcrypt.so.1.1.0
ffff9797e000-ffff97986000 rw-p 00000000 00:00 0
ffff97990000-ffff97a05000 r-xp 00000000 103:01 12836588                  /usr/lib/aarch64-linux-gnu/libgmp.so.10.4.1
ffff97a05000-ffff97a15000 ---p 00075000 103:01 12836588                  /usr/lib/aarch64-linux-gnu/libgmp.so.10.4.1
ffff97a15000-ffff97a16000 r--p 00075000 103:01 12836588                  /usr/lib/aarch64-linux-gnu/libgmp.so.10.4.1
ffff97a16000-ffff97a17000 rw-p 00076000 103:01 12836588                  /usr/lib/aarch64-linux-gnu/libgmp.so.10.4.1
ffff97a20000-ffff97a38000 r-xp 00000000 103:01 45145360                  /usr/lib/aarch64-linux-gnu/libz.so.1.2.11
ffff97a38000-ffff97a48000 ---p 00018000 103:01 45145360                  /usr/lib/aarch64-linux-gnu/libz.so.1.2.11
ffff97a48000-ffff97a49000 r--p 00018000 103:01 45145360                  /usr/lib/aarch64-linux-gnu/libz.so.1.2.11
ffff97a49000-ffff97a4a000 rw-p 00019000 103:01 45145360                  /usr/lib/aarch64-linux-gnu/libz.so.1.2.11
ffff97a50000-ffff9800c000 r-xp 00000000 103:01 11617338                  /usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3.0
ffff9800c000-ffff9801b000 ---p 005bc000 103:01 11617338                  /usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3.0
ffff9801b000-ffff98032000 r--p 005bb000 103:01 11617338                  /usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3.0
ffff98032000-ffff98036000 rw-p 005d2000 103:01 11617338                  /usr/local/rvm/rubies/ruby-3.3.0/lib/libruby.so.3.3.0
ffff98036000-ffff9804b000 rw-p 00000000 00:00 0
ffff9804d000-ffff98078000 r-xp 00000000 103:01 45140138                  /usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
ffff9807b000-ffff9807f000 rw-p 00000000 00:00 0
ffff98083000-ffff98085000 rw-p 00000000 00:00 0
ffff98085000-ffff98086000 r--p 00000000 00:00 0                          [vvar]
ffff98086000-ffff98087000 r-xp 00000000 00:00 0                          [vdso]
ffff98087000-ffff98089000 r--p 0002a000 103:01 45140138                  /usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
ffff98089000-ffff9808b000 rw-p 0002c000 103:01 45140138                  /usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
ffffd32f0000-ffffd3cef000 rw-p 00000000 00:00 0                          [stack]


Segmentation fault (core dumped)
```

Please advice.

**Comment by CamJN** [comment]
Unfortunately I believe this is an upstream issue with either: how rvm compiles ruby, ruby itself, or possibly (though _very_ unlikely) the linux kernel's vDSO implementation. If you could install the ruby debug symbols and get a symbolicated backtrace that would help us be sure.

The important bits I can see in the crash report are:

- the address 0xffffffffffffffff is pretty clearly intended to be invalid
- the c backtrace only includes ruby and linux-vdso traces

**Comment by hopewise** [comment]
I can provide details about the OS if that would help:

```
docker exec -it 716a5c765022 bash
root@716a5c765022:/home/app/webapp# which ruby
/usr/bin/ruby
root@716a5c765022:/home/app/webapp# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

And for the CPU:

```
lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               ARM
  Model name:            Neoverse-N1
    Model:               1
    Thread(s) per core:  1
    Core(s) per cluster: 2
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r3p1
    BogoMIPS:            243.75
    Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
Caches (sum of all):
  L1d:                   128 KiB (2 instances)
  L1i:                   128 KiB (2 instances)
  L2:                    2 MiB (2 instances)
  L3:                    32 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
Vulnerabilities:
  Gather data sampling:  Not affected
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Mitigation; CSV2, BHB
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

Is there any ready to use docker base rather than `phusion/passenger-ruby33:latest` ?
Also, and directions for installing ruby debug symbols?

**Comment by CamJN** [comment]
There's a new image released that uses a newer ubuntu version as the base, perhaps that will help.

**Comment by ajhodgson** [comment]
Closing as stale. Please open a new issue if required.
